# Netlify configuration for YICA/YiRage documentation

[build]
  publish = "docs/_build/html"
  command = "cd docs && pip install -r requirements.txt && python -m sphinx -b html . _build/html"

[build.environment]
  PYTHON_VERSION = "3.10"
  PIP_CACHE_DIR = ".pip_cache"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Redirects for clean URLs
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api"
  to = "/api/README.html"
  status = 301

[[redirects]]
  from = "/tutorials"
  to = "/tutorials/README.html"
  status = 301

[[redirects]]
  from = "/architecture"
  to = "/architecture/README.html"
  status = 301

# 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
